[package]
name = "classicube-blockref-plugin"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git"}
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
rand = "0.7.3"
